/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Toast;
import dao.BussinessException;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import pojos.Aluno;
import pojos.Aula;
import pojos.AlunoAula;

/**
 *
 * @author 
 */
public class AlunoAulaDialog extends javax.swing.JDialog {

    /**
     * Creates new form ClienteDialog
     */
    private final String busca1 = "Busca por código",
            busca2 = "Busca por nome";
    Main main;
    Toast msg;
    List<Aluno> list_atual;
    List<AlunoAula> list_atual_atribuidos;
    List<Aluno> atributos;
    Aula aula;

    public AlunoAulaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        main = (Main) parent;
        this.setLocationRelativeTo(null);
        //Atualizar tabela
        String toolTip = "Notas de Aluno";
        atribuir.setToolTipText("Atribuir " + toolTip);
        naoAtribuir.setToolTipText("Não Atribuir " + toolTip);

    }

    public void setAula(Aula aula) {
        this.aula = aula;
        jLabel2.setText(("AULA: " + (aula.getNumero()<10?"0"+aula.getNumero():aula.getNumero()+"")+
                " - PROFESSOR: "+aula.getProfessor().getFuncionario().getPessoa().getNome()+
                " - TIPO: "+aula.getTipo().getNome()).toUpperCase());
        updateList(aula);
        updateJTable();
        updateJTableAtribuida();
    }

    public void addRowTableModel(DefaultTableModel model, Aluno obj) {
        model.addRow(new Object[]{
            obj.getPessoa().getNome()+" "+obj.getPessoa().getSobrenome()
        });
    }

    public void addRowTableModelAtribuida(DefaultTableModel model, AlunoAula obj) {
        model.addRow(new Object[]{
            obj.getAluno().getPessoa().getNome()+" "+obj.getAluno().getPessoa().getSobrenome()
        });
    }

    public void updateList(Aula obj) {
        list_atual = new ArrayList<Aluno>();
        list_atual_atribuidos = new ArrayList<AlunoAula>();
        for (AlunoAula salest : obj.getAlunoAulas()) {
            list_atual_atribuidos.add(salest);
        }

        try {
            List<Aluno> objs = main.control.getAlunoDAO().findAll();
            for (Aluno atr : objs) {
                boolean flag = false;
                for (AlunoAula aden : list_atual_atribuidos) {
                    if (aden.getAluno().getId() == atr.getId()) {
                        flag = true;
                        break;
                    }
                }
                if (!flag) {
                    list_atual.add(atr);
                }
            }
        } catch (BussinessException ex) {
            main.control.messageErroBussiness(ex);
        }

    }

    public void updateJTable() {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        model.setNumRows(0);
        for (Aluno obj : list_atual) {
            addRowTableModel(model, obj);
        }
    }

    public void updateJTableBusca(List<Aluno> list) {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        model.setNumRows(0);
        for (Aluno obj : list) {
            addRowTableModel(model, obj);
        }
    }

    public void updateJTableAtribuida() {
        DefaultTableModel model = (DefaultTableModel) tabelaAtribuida.getModel();
        model.setNumRows(0);
        for (AlunoAula obj : aula.getAlunoAulas()) {
            addRowTableModelAtribuida(model, obj);
        }
    }

    public void updateJTableBuscaAtribuida(List<AlunoAula> list) {
        DefaultTableModel model = (DefaultTableModel) tabelaAtribuida.getModel();
        model.setNumRows(0);
        for (AlunoAula obj : list) {
            addRowTableModelAtribuida(model, obj);
        }
    }

    public void focusGained(JTextField jtf, String field) {
        if (jtf.getText().equals(field)) {
            jtf.setText("");
        }
        jtf.setForeground(Color.BLACK);
    }

    public void focusLost(JTextField jtf, String field) {
        if (jtf.getText().equals("")) {
            jtf.setText(field);
        }
        if (jtf.getText().equals(field)) {
            jtf.setForeground(new Color(153, 153, 153));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAtribuida = new javax.swing.JTable();
        busca_nome = new javax.swing.JTextField();
        atribuir = new javax.swing.JButton();
        naoAtribuir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        busca_nome_atribuidos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GERENCIAR ALUNOS DA AULA");

        tabelaAtribuida.setAutoCreateRowSorter(true);
        tabelaAtribuida.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tabelaAtribuida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aluno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaAtribuida);

        busca_nome.setForeground(new java.awt.Color(153, 153, 153));
        busca_nome.setText("Busca por nome");
        busca_nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                busca_nomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                busca_nomeFocusLost(evt);
            }
        });
        busca_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busca_nomeKeyPressed(evt);
            }
        });

        atribuir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons8_add_user_male_28px.png"))); // NOI18N
        atribuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atribuirActionPerformed(evt);
            }
        });

        naoAtribuir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons8_denied_28px.png"))); // NOI18N
        naoAtribuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naoAtribuirActionPerformed(evt);
            }
        });

        tabela.setAutoCreateRowSorter(true);
        tabela.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aluno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabela);

        busca_nome_atribuidos.setForeground(new java.awt.Color(153, 153, 153));
        busca_nome_atribuidos.setText("Busca por nome");
        busca_nome_atribuidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                busca_nome_atribuidosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                busca_nome_atribuidosFocusLost(evt);
            }
        });
        busca_nome_atribuidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busca_nome_atribuidosKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("AULA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(atribuir, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(naoAtribuir, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                            .addComponent(busca_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(busca_nome_atribuidos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(busca_nome_atribuidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busca_nome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(atribuir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(naoAtribuir)
                        .addGap(53, 53, 53))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void busca_nomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busca_nomeKeyPressed
        List<Aluno> list = new ArrayList<>();
        updateList(aula);
        updateJTable();
        boolean flag = false;
        for (Aluno list1 : list_atual) {
            if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE
                    && !(list1.getPessoa().getNome()).toUpperCase().contains(
                            (busca_nome.getText().substring(0, busca_nome.getText().length() - 1)).toUpperCase()
                    )) {
                flag = true;
            } else if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE
                    && !(list1.getPessoa().getNome()).toUpperCase().contains(
                            (busca_nome.getText() + evt.getKeyChar()).toUpperCase()
                    )) {
                flag = true;
            } else {
                list.add(list1);
            }
        }
        list_atual = list;
        updateJTableBusca(list);
    }//GEN-LAST:event_busca_nomeKeyPressed

    private void busca_nomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_busca_nomeFocusLost
        focusLost(busca_nome, busca2);
    }//GEN-LAST:event_busca_nomeFocusLost

    private void busca_nomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_busca_nomeFocusGained
        focusGained(busca_nome, busca2);
    }//GEN-LAST:event_busca_nomeFocusGained

    private void atribuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atribuirActionPerformed
        int[] rows = tabela.getSelectedRows();

        if (rows.length == 0) {
            msg = new Toast("Você tem que fazer uma seleção dos alunos a asignar para a aula", 3000);
            msg.showToast();
        } else {
            try {
                for (int row : rows) {
                    AlunoAula obj = new AlunoAula(list_atual.get(row),
                            aula);

                    main.control.getAlunoAulaDAO().save(obj);
                    aula = main.control.getAulaDAO().get(aula.getId());
                }

                updateList(aula);
                updateJTable();
                updateJTableAtribuida();

            } catch (BussinessException ex) {
                main.control.messageErroBussiness(ex);
            }

        }
    }//GEN-LAST:event_atribuirActionPerformed

    private void naoAtribuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoAtribuirActionPerformed
        int[] rows = tabelaAtribuida.getSelectedRows();
        if (rows.length == 0) {
            msg = new Toast("Você tem que fazer uma seleção dos alunos a apagar para a aula", 3000);
            msg.showToast();
        } else {
            try {

                for (int row : rows) {
                    main.control.getAlunoAulaDAO().delete(list_atual_atribuidos.get(row).getId());
                    aula = main.control.getAulaDAO().get(aula.getId());
                }
                updateList(aula);
                updateJTable();
                updateJTableAtribuida();
            } catch (BussinessException ex) {
                main.control.messageErroBussiness(ex);
            }

        }
    }//GEN-LAST:event_naoAtribuirActionPerformed

    private void busca_nome_atribuidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_busca_nome_atribuidosFocusGained
        focusGained(busca_nome_atribuidos, busca2);
    }//GEN-LAST:event_busca_nome_atribuidosFocusGained

    private void busca_nome_atribuidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_busca_nome_atribuidosFocusLost
        focusLost(busca_nome_atribuidos, busca2);
    }//GEN-LAST:event_busca_nome_atribuidosFocusLost

    private void busca_nome_atribuidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busca_nome_atribuidosKeyPressed
        List<AlunoAula> list = new ArrayList<>();
        updateList(aula);
        updateJTableAtribuida();
        boolean flag = false;
        for (AlunoAula list1 : list_atual_atribuidos) {
            if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE
                    && !(list1.getAluno().getPessoa().getNome()).toUpperCase().contains(
                            (busca_nome_atribuidos.getText().substring(0, busca_nome_atribuidos.getText().length() - 1)).toUpperCase()
                    )) {
                flag = true;
            } else if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE
                    && !(list1.getAluno().getPessoa().getNome()).toUpperCase().contains(
                            (busca_nome_atribuidos.getText() + evt.getKeyChar()).toUpperCase()
                    )) {
                flag = true;
            } else {
                list.add(list1);
            }
        }
        list_atual_atribuidos = list;
        updateJTableBuscaAtribuida(list);
    }//GEN-LAST:event_busca_nome_atribuidosKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlunoAulaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlunoAulaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlunoAulaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlunoAulaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
      

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlunoAulaDialog dialog = new AlunoAulaDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atribuir;
    private javax.swing.JTextField busca_nome;
    private javax.swing.JTextField busca_nome_atribuidos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton naoAtribuir;
    private javax.swing.JTable tabela;
    private javax.swing.JTable tabelaAtribuida;
    // End of variables declaration//GEN-END:variables
}
