package pojos;
// Generated 09-may-2022 18:22:43 by Hibernate Tools 4.3.1



/**
 * AlunoExame generated by hbm2java
 */
public class AlunoExame  implements java.io.Serializable {


     private Integer id;
     private Aluno aluno;
     private Exame exame;
     private int avaliacaoQuantitativa;
     private String avaliacaoQualitativa;

    public AlunoExame() {
    }

    public AlunoExame(Aluno aluno, Exame exame, int avaliacaoQuantitativa, String avaliacaoQualitativa) {
       this.aluno = aluno;
       this.exame = exame;
       this.avaliacaoQuantitativa = avaliacaoQuantitativa;
       this.avaliacaoQualitativa = avaliacaoQualitativa;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Aluno getAluno() {
        return this.aluno;
    }
    
    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }
    public Exame getExame() {
        return this.exame;
    }
    
    public void setExame(Exame exame) {
        this.exame = exame;
    }
    
    public int getAvaliacaoQuantitativa() {
        return this.avaliacaoQuantitativa;
    }
    
    public void setAvaliacaoQuantitativa(int avaliacaoQuantitativa) {
        this.avaliacaoQuantitativa = avaliacaoQuantitativa;
    }
    public String getAvaliacaoQualitativa() {
        return this.avaliacaoQualitativa;
    }
    
    public void setAvaliacaoQualitativa(String avaliacaoQualitativa) {
        this.avaliacaoQualitativa = avaliacaoQualitativa;
    }




}


