package pojos;
// Generated 05-may-2022 17:44:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aluno generated by hbm2java
 */
public class Aluno  implements java.io.Serializable {


     private int id;
     private Pessoa pessoa;
     private Transporte transporte;
     private String fichaRequerimento;
     private String cartaoVacina;
     private Set<AlunoAula> alunoAulas = new HashSet<AlunoAula>(0);
     private Set<Inscricao> inscricaos = new HashSet<Inscricao>(0);
     private Set<AlunoExame> alunoExames = new HashSet<AlunoExame>(0);

    public Aluno() {
    }

	
    public Aluno(Pessoa pessoa, Transporte transporte, String fichaRequerimento, String cartaoVacina) {
        this.pessoa = pessoa;
        this.transporte = transporte;
        this.fichaRequerimento = fichaRequerimento;
        this.cartaoVacina = cartaoVacina;
    }
    public Aluno(Pessoa pessoa, Transporte transporte, String fichaRequerimento, String cartaoVacina, Set<AlunoAula> alunoAulas, Set<Inscricao> inscricaos, Set<AlunoExame> alunoExames) {
       this.pessoa = pessoa;
       this.transporte = transporte;
       this.fichaRequerimento = fichaRequerimento;
       this.cartaoVacina = cartaoVacina;
       this.alunoAulas = alunoAulas;
       this.inscricaos = inscricaos;
       this.alunoExames = alunoExames;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Transporte getTransporte() {
        return this.transporte;
    }
    
    public void setTransporte(Transporte transporte) {
        this.transporte = transporte;
    }
    public String getFichaRequerimento() {
        return this.fichaRequerimento;
    }
    
    public void setFichaRequerimento(String fichaRequerimento) {
        this.fichaRequerimento = fichaRequerimento;
    }
    public String getCartaoVacina() {
        return this.cartaoVacina;
    }
    
    public void setCartaoVacina(String cartaoVacina) {
        this.cartaoVacina = cartaoVacina;
    }
    public Set<AlunoAula> getAlunoAulas() {
        return this.alunoAulas;
    }
    
    public void setAlunoAulas(Set<AlunoAula> alunoAulas) {
        this.alunoAulas = alunoAulas;
    }
    public Set<Inscricao> getInscricaos() {
        return this.inscricaos;
    }
    
    public void setInscricaos(Set<Inscricao> inscricaos) {
        this.inscricaos = inscricaos;
    }
    public Set<AlunoExame> getAlunoExames() {
        return this.alunoExames;
    }
    
    public void setAlunoExames(Set<AlunoExame> alunoExames) {
        this.alunoExames = alunoExames;
    }




}


