package pojos;
// Generated 05-may-2022 17:44:55 by Hibernate Tools 4.3.1



/**
 * AlunoAula generated by hbm2java
 */
public class AlunoAula  implements java.io.Serializable {


     private Integer id;
     private Aluno aluno;
     private Aula aula;

    public AlunoAula() {
    }

    public AlunoAula(Aluno aluno, Aula aula) {
       this.aluno = aluno;
       this.aula = aula;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Aluno getAluno() {
        return this.aluno;
    }
    
    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }
    public Aula getAula() {
        return this.aula;
    }
    
    public void setAula(Aula aula) {
        this.aula = aula;
    }




}


