package pojos;
// Generated 05-may-2022 17:44:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bairro generated by hbm2java
 */
public class Bairro  implements java.io.Serializable {


     private Integer id;
     private Municipio municipio;
     private String nome;
     private Set<Residencia> residencias = new HashSet<Residencia>(0);

    public Bairro() {
    }

	
    public Bairro(Municipio municipio, String nome) {
        this.municipio = municipio;
        this.nome = nome;
    }
    public Bairro(Municipio municipio, String nome, Set<Residencia> residencias) {
       this.municipio = municipio;
       this.nome = nome;
       this.residencias = residencias;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Residencia> getResidencias() {
        return this.residencias;
    }
    
    public void setResidencias(Set<Residencia> residencias) {
        this.residencias = residencias;
    }




}


