package pojos;
// Generated 05-may-2022 17:44:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Set<Exame> exames = new HashSet<Exame>(0);
     private Set<Inscricao> inscricaos = new HashSet<Inscricao>(0);

    public Categoria() {
    }

	
    public Categoria(String nome) {
        this.nome = nome;
    }
    public Categoria(String nome, Set<Exame> exames, Set<Inscricao> inscricaos) {
       this.nome = nome;
       this.exames = exames;
       this.inscricaos = inscricaos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Exame> getExames() {
        return this.exames;
    }
    
    public void setExames(Set<Exame> exames) {
        this.exames = exames;
    }
    public Set<Inscricao> getInscricaos() {
        return this.inscricaos;
    }
    
    public void setInscricaos(Set<Inscricao> inscricaos) {
        this.inscricaos = inscricaos;
    }




}


