package pojos;
// Generated 09-may-2022 18:22:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private int id;
     private Cargo cargo;
     private Pessoa pessoa;
     private Professor professor;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Instructor instructor;

    public Funcionario() {
    }

	
    public Funcionario(Cargo cargo, Pessoa pessoa) {
        this.cargo = cargo;
        this.pessoa = pessoa;
    }
    public Funcionario(Cargo cargo, Pessoa pessoa, Professor professor, Set<Usuario> usuarios, Instructor instructor) {
       this.cargo = cargo;
       this.pessoa = pessoa;
       this.professor = professor;
       this.usuarios = usuarios;
       this.instructor = instructor;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Professor getProfessor() {
        return this.professor;
    }
    
    public void setProfessor(Professor professor) {
        this.professor = professor;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    public Instructor getInstructor() {
        return this.instructor;
    }
    
    public void setInstructor(Instructor instructor) {
        this.instructor = instructor;
    }




}


