package pojos;
// Generated 09-may-2022 18:22:43 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Inscricao generated by hbm2java
 */
public class Inscricao  implements java.io.Serializable {


     private Integer id;
     private Aluno aluno;
     private Categoria categoria;
     private TipoInscricao tipoInscricao;
     private Date data;

    public Inscricao() {
    }

    public Inscricao(Aluno aluno, Categoria categoria, TipoInscricao tipoInscricao, Date data) {
       this.aluno = aluno;
       this.categoria = categoria;
       this.tipoInscricao = tipoInscricao;
       this.data = data;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Aluno getAluno() {
        return this.aluno;
    }
    
    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public TipoInscricao getTipoInscricao() {
        return this.tipoInscricao;
    }
    
    public void setTipoInscricao(TipoInscricao tipoInscricao) {
        this.tipoInscricao = tipoInscricao;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

}


