package pojos;
// Generated 05-may-2022 17:44:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Instructor generated by hbm2java
 */
public class Instructor  implements java.io.Serializable {


     private int id;
     private Pessoa pessoa;
     private Set<Exame> exames = new HashSet<Exame>(0);

    public Instructor() {
    }

	
    public Instructor(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Instructor(Pessoa pessoa, Set<Exame> exames) {
       this.pessoa = pessoa;
       this.exames = exames;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Set<Exame> getExames() {
        return this.exames;
    }
    
    public void setExames(Set<Exame> exames) {
        this.exames = exames;
    }




}


