package pojos;
// Generated 09-may-2022 18:22:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Instructor generated by hbm2java
 */
public class Instructor  implements java.io.Serializable {


     private int id;
     private Funcionario funcionario;
     private Set<Exame> exames = new HashSet<Exame>(0);

    public Instructor() {
    }

	
    public Instructor(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Instructor(Funcionario funcionario, Set<Exame> exames) {
       this.funcionario = funcionario;
       this.exames = exames;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Set<Exame> getExames() {
        return this.exames;
    }
    
    public void setExames(Set<Exame> exames) {
        this.exames = exames;
    }




}


