package pojos;
// Generated 05-may-2022 17:44:55 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private Integer id;
     private Residencia residencia;
     private String nome;
     private String sobrenome;
     private String passaporte;
     private String genero;
     private Date dataNascimento;
     private String email;
     private String telefone;
     private Aluno aluno;
     private Professor professor;
     private Funcionario funcionario;
     private Instructor instructor;

    public Pessoa() {
    }

	
    public Pessoa(Residencia residencia, String nome, String sobrenome, String passaporte, String genero, Date dataNascimento, String telefone) {
        this.residencia = residencia;
        this.nome = nome;
        this.sobrenome = sobrenome;
        this.passaporte = passaporte;
        this.genero = genero;
        this.dataNascimento = dataNascimento;
        this.telefone = telefone;
    }
    public Pessoa(Residencia residencia, String nome, String sobrenome, String passaporte, String genero, Date dataNascimento, String email, String telefone, Aluno aluno, Professor professor, Funcionario funcionario, Instructor instructor) {
       this.residencia = residencia;
       this.nome = nome;
       this.sobrenome = sobrenome;
       this.passaporte = passaporte;
       this.genero = genero;
       this.dataNascimento = dataNascimento;
       this.email = email;
       this.telefone = telefone;
       this.aluno = aluno;
       this.professor = professor;
       this.funcionario = funcionario;
       this.instructor = instructor;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Residencia getResidencia() {
        return this.residencia;
    }
    
    public void setResidencia(Residencia residencia) {
        this.residencia = residencia;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }
    public String getPassaporte() {
        return this.passaporte;
    }
    
    public void setPassaporte(String passaporte) {
        this.passaporte = passaporte;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public Aluno getAluno() {
        return this.aluno;
    }
    
    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }
    public Professor getProfessor() {
        return this.professor;
    }
    
    public void setProfessor(Professor professor) {
        this.professor = professor;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Instructor getInstructor() {
        return this.instructor;
    }
    
    public void setInstructor(Instructor instructor) {
        this.instructor = instructor;
    }




}


