package pojos;
// Generated 09-may-2022 18:22:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Professor generated by hbm2java
 */
public class Professor  implements java.io.Serializable {


     private int id;
     private Funcionario funcionario;
     private Set<Aula> aulas = new HashSet<Aula>(0);

    public Professor() {
    }

	
    public Professor(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Professor(Funcionario funcionario, Set<Aula> aulas) {
       this.funcionario = funcionario;
       this.aulas = aulas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Set<Aula> getAulas() {
        return this.aulas;
    }
    
    public void setAulas(Set<Aula> aulas) {
        this.aulas = aulas;
    }




}


