package pojos;
// Generated 05-may-2022 17:44:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Professor generated by hbm2java
 */
public class Professor  implements java.io.Serializable {


     private int id;
     private Pessoa pessoa;
     private Set<Aula> aulas = new HashSet<Aula>(0);

    public Professor() {
    }

	
    public Professor(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Professor(Pessoa pessoa, Set<Aula> aulas) {
       this.pessoa = pessoa;
       this.aulas = aulas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Set<Aula> getAulas() {
        return this.aulas;
    }
    
    public void setAulas(Set<Aula> aulas) {
        this.aulas = aulas;
    }




}


