package pojos;
// Generated 09-may-2022 18:22:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoInscricao generated by hbm2java
 */
public class TipoInscricao  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Set<Inscricao> inscricaos = new HashSet<Inscricao>(0);

    public TipoInscricao() {
    }

	
    public TipoInscricao(String nome) {
        this.nome = nome;
    }
    public TipoInscricao(String nome, Set<Inscricao> inscricaos) {
       this.nome = nome;
       this.inscricaos = inscricaos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Inscricao> getInscricaos() {
        return this.inscricaos;
    }
    
    public void setInscricaos(Set<Inscricao> inscricaos) {
        this.inscricaos = inscricaos;
    }




}


