package pojos;
// Generated 09-may-2022 18:22:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoTransporte generated by hbm2java
 */
public class TipoTransporte  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Set<Transporte> transportes = new HashSet<Transporte>(0);

    public TipoTransporte() {
    }

	
    public TipoTransporte(String nome) {
        this.nome = nome;
    }
    public TipoTransporte(String nome, Set<Transporte> transportes) {
       this.nome = nome;
       this.transportes = transportes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Transporte> getTransportes() {
        return this.transportes;
    }
    
    public void setTransportes(Set<Transporte> transportes) {
        this.transportes = transportes;
    }




}


