package pojos;
// Generated 09-may-2022 18:22:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipo generated by hbm2java
 */
public class Tipo  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Set<Exame> exames = new HashSet<Exame>(0);
     private Set<Aula> aulas = new HashSet<Aula>(0);

    public Tipo() {
    }

	
    public Tipo(String nome) {
        this.nome = nome;
    }
    public Tipo(String nome, Set<Exame> exames, Set<Aula> aulas) {
       this.nome = nome;
       this.exames = exames;
       this.aulas = aulas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Exame> getExames() {
        return this.exames;
    }
    
    public void setExames(Set<Exame> exames) {
        this.exames = exames;
    }
    public Set<Aula> getAulas() {
        return this.aulas;
    }
    
    public void setAulas(Set<Aula> aulas) {
        this.aulas = aulas;
    }




}


