package pojos;
// Generated 09-may-2022 18:22:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Transporte generated by hbm2java
 */
public class Transporte  implements java.io.Serializable {


     private Integer id;
     private TipoTransporte tipoTransporte;
     private double peso;
     private String marca;
     private String modelo;
     private String cor;
     private String matricula;
     private String numCirculacao;
     private Set<Aluno> alunos = new HashSet<Aluno>(0);

    public Transporte() {
    }

	
    public Transporte(TipoTransporte tipoTransporte, double peso, String marca, String modelo, String cor, String matricula, String numCirculacao) {
        this.tipoTransporte = tipoTransporte;
        this.peso = peso;
        this.marca = marca;
        this.modelo = modelo;
        this.cor = cor;
        this.matricula = matricula;
        this.numCirculacao = numCirculacao;
    }
    public Transporte(TipoTransporte tipoTransporte, double peso, String marca, String modelo, String cor, String matricula, String numCirculacao, Set<Aluno> alunos) {
       this.tipoTransporte = tipoTransporte;
       this.peso = peso;
       this.marca = marca;
       this.modelo = modelo;
       this.cor = cor;
       this.matricula = matricula;
       this.numCirculacao = numCirculacao;
       this.alunos = alunos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TipoTransporte getTipoTransporte() {
        return this.tipoTransporte;
    }
    
    public void setTipoTransporte(TipoTransporte tipoTransporte) {
        this.tipoTransporte = tipoTransporte;
    }
    public double getPeso() {
        return this.peso;
    }
    
    public void setPeso(double peso) {
        this.peso = peso;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getCor() {
        return this.cor;
    }
    
    public void setCor(String cor) {
        this.cor = cor;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public String getNumCirculacao() {
        return this.numCirculacao;
    }
    
    public void setNumCirculacao(String numCirculacao) {
        this.numCirculacao = numCirculacao;
    }
    public Set<Aluno> getAlunos() {
        return this.alunos;
    }
    
    public void setAlunos(Set<Aluno> alunos) {
        this.alunos = alunos;
    }




}


